### ISSUE TITLE
can't start up the game with this mod in steamdeck

### ISSUE THREAD

**Issue by pkoko** [sneakyevil/SleepingDogs-RenderTweaker#2]
steamdeck os version : 3.4.10
game version: official steam version
 After extracting the file in the game folder and added the start option. the game starts in a few sec, it quit after showing the the Havok logo

**Comment by sneakyevil** [comment]
Did you download the executable from point 1 that explain to read another readme?

**Comment by pkoko** [comment]
OK, I download the exe in readme and replace the one in the game folder. the game could startup as before. But when I press F10, the game was paused, no any popup shows but it resumes when press F10 again.

**Comment by sneakyevil** [comment]
Try download new `v1.4.1` version.

**Comment by pkoko** [comment]
emmm, use 1.4.1, the issue didn't change

**Comment by sneakyevil** [comment]
This might be related issue to fullscreen atm, you might try launching it in windowed and tweak some stuff and saving it and then switching to fullscreen.

**Comment by sneakyevil** [comment]
I just fixed the fullscreen rendering in the `v1.4.2`, let me know if that works fine for you.

**Comment by pkoko** [comment]
just update the 1.4.2. the tweak window could shows up now with window mode (cheers). but in fullscreen it still struck as before

**Comment by sneakyevil** [comment]
I closing this issue since I have no idea if this is just issue on linux and has something to do with wine/proton layer. Seems to work fine on windows and been tested by few people on different configuration under Windows 10. If you find out if its something related to some settings let me know.
